{
 "title": "Jenkins jobs monitor",
 "description": "Dashboard to monitor jenkins jobs/pipelines execution",
 "tags": [
  "jenkins",
  "cicd"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "jnk",
    "label": "jenkins",
    "query": {
     "query": "label_values(default_jenkins_up,job)"
    }
   },
   {
    "name": "job_name",
    "query": {
     "query": "label_values(default_jenkins_builds_last_build_duration_milliseconds{job=\"$jnk\", buildable=\"true\"},jenkins_job)"
    }
   },
   { "name": "resolution", "label": "Resolution", "query": "30s, 1m" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Job details",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "default_jenkins_builds_health_score{job=~\"$jnk\", jenkins_job=~\"$job_name\"}",
     "legendFormat": "job_name"
    }
   ]
  },
  {
   "title": "Job duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "default_jenkins_builds_last_build_duration_milliseconds{job=~\"$jnk\", jenkins_job=~\"$job_name\"}",
     "legendFormat": "Last build"
    }
   ]
  },
  {
   "title": "Stages duration",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "default_jenkins_builds_last_stage_duration_milliseconds_summary_sum{job=~\"$jnk\", jenkins_job=~\"$job_name\"}",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Last build number",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "default_jenkins_builds_available_builds_count{job=~\"$jnk\", jenkins_job=~\"$job_name\"}",
     "legendFormat": "build_number"
    }
   ]
  },
  {
   "title": "Last build result",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "default_jenkins_builds_last_build_result{job=~\"$jnk\", jenkins_job=~\"$job_name\"}",
     "legendFormat": "build_number"
    }
   ]
  },
  {
   "title": "Last start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "${__to} - default_jenkins_builds_last_build_start_time_milliseconds{job=~\"$jnk\", jenkins_job=~\"$job_name\"}",
     "legendFormat": "build_number"
    }
   ]
  }
 ]
}