services:
  prometheus:
    image: prom/prometheus:v3.0.1@sha256:565ee86501224ebbb98fc10b332fa54440b100469924003359edf49cbce374bd
    container_name: prometheus
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'    
    volumes:
      - ./prometheus/prometheus-config.yaml:/etc/prometheus/prometheus.yml
      - v_prometheus_data:/prometheus
    ports:
      - 9090:9090
    networks:
      - n_metrics
      - n_ci_cd

  grafana:
    image: grafana/grafana:11.4.0@sha256:d8ea37798ccc41061a62ab080f2676dda6bf7815558499f901bdb0f533a456fb
    container_name: grafana
    restart: always
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./dashboards/:/etc/grafana/local-dashs
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - "3000:3000"
    networks:
      - n_metrics
      - n_ci_cd

networks:
  n_metrics:
    name: n_metrics
  n_ci_cd:
    name: n_ci_cd    
    external: true

volumes:
  v_prometheus_data: