# https://prometheus.io/docs/prometheus/latest/configuration/configuration/#configuration

global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'jenkins'
    scrape_interval: 1s
    static_configs:
      - targets: ['jenkins:8080']
    metrics_path: /prometheus